name: EPG Cron Update

on:
  workflow_dispatch:
  schedule:
    # This runs at exactly 12:00 UTC every day
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 25.x
        uses: actions/setup-node@v3
        with:
          node-version: 25.x
          cache: 'npm'
      - name: Install python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          check-latest: true

      - name: Start EPG
        run: chmod +x ./start.sh && ./start.sh

      - name: Update EPG contents
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Chore: Update EPG Content"
          branch: epg